apiVersion: v1
kind: Service
metadata:
  name: comicbox-service
  namespace: monitoring

spec:
  selector:
    app: comicbox
  type: NodePort
  ports:
    - port: 30001
      targetPort: 3001
      nodePort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: comicbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: comicbox
    spec:
      containers:
        - name: comicbox
          image: rivethead42/comicbox
          ports:
            - containerPort: 3000
